apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: {{ .Release.Name }}
            image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
            volumeMounts:
            {{- range .Values.secrets.items }}
            - name: {{ .name }}
              mountPath: /etc/accountant/{{ .name }}
            {{- end }}
            - name: config
              mountPath: /app/config
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: {{ .Release.Name }}
          {{ range .Values.secrets.items }}
          - name: {{ .name }}
            secret:
              secretName: {{ .name }}
              items:
{{ toYaml .content | indent 14 }}
          {{- end }}
